function [fitresult, gof] = createFit(string_len, fundfreq1)
%CREATEFIT(STRING_LEN,FUNDFREQ1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : string_len
%      Y Output: fundfreq1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Jan-2018 13:06:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( string_len, fundfreq1 );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [91.4507299263746 -1.0029034040039];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'fundfreq1 vs. string_len', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel string_len
ylabel fundfreq1
grid on


