scale_length = [3.66 1.83 1.22];
inv_scale_length = [0.273224044 0.546448087 0.819672131];
freq = [0.869565217 1.87090739 2.702702703];
freq_err = [0.02268431 0.105008834 0.219138057];

string_len = [0.65 0.6 0.55 0.5 0.45 0.575];
fundfreq1 = [140.115 152.047 166.881 184.187 203.966 159.464];
err = [2.5 2.5 2.5 2.5 2.5 2.5];

tension = [44.59626 39.69126 34.78626 29.88126 24.97626 20.07126];
fundfreq2 = [184.187 174.298 161.936 149.575 137.213 122.379];


%CREATEFIT1(TENSION,FUNDFREQ2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : tension
%      Y Output: fundfreq2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Jan-2018 13:13:33


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( tension, fundfreq2 );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [26.2238415167157 0.513523299043565];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'fundfreq2 vs. tension', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel tension
ylabel fundfreq2
grid on


